FROM debian:stable
  

RUN apt-get update && apt-get install -y --force-yes apache2 &&\
apt-get install -y git

RUN "ls" "/var/www"
WORKDIR /var/www/html
RUN git clone https://github.com/edureka-devops/projCert.git 
RUN "ls" "/var/www/html"
EXPOSE 80 443



#VOLUME ["/var/www/html", "/var/log/apache2", "/etc/apache2"]

#ENTRYPOINT ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]

